apiVersion: v1
kind: Pod
metadata:
  name: demo-pod3
spec:
  containers:
    - name: nginx
      
      image: nginx:latest
      env:
        - name: greetings
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: welcome_message
              
